# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-08 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_city_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
